### ISSUE TITLE
Cant not see new printer to add

### ISSUE THREAD

**Issue by sohail579** [just-trey/AnkerMake-M5-Profile#11]
I have copied the files required as per instructions in to the profile folder however it wont see them and does not show me anything in Cura.  what am i doing wrong?

**Comment by just-trey** [comment]
Can you send me a screenshot of the location you put the files?

**Comment by sohail579** [comment]
sorry it was my mistake i had Cura 5.1 installed and used the folder but when i click an stl it would open in 5.2 didnt realise when you upgrade it doesnt remove the old version
