### ISSUE TITLE
Q: Cura base plate obscuring underside

### ISSUE THREAD

**Issue by tomjn** [just-trey/AnkerMake-M5-Profile#12]
If I twist the view around in AnkerMake I can see the bottom of the print, but I can't do the same in Cura as it just shows the printbed model with the anker logo/grid. Is this expected?

I wonder if a version with only top faces might be better so it isn't rendered when viewed from underneath

**Comment by gitsf** [comment]
That is how it appears for me as well. I too would like to be able to see the view of the model and not the print bed when viewing from a bottom angle.

**Comment by just-trey** [comment]
@gitsf and @tomjn question for you. I want to keep the branding and look close. I made the png more transparent as a test. Would this meet the need? I know it is purely aesthetic. 

top
![image](https://user-images.githubusercontent.com/10281380/211170778-71753de9-c923-4c0d-bd31-188383dcdd3e.png)
Bottom
![image](https://user-images.githubusercontent.com/10281380/211170793-c0d57319-f425-4525-8871-19052b585da4.png)

**Comment by tomjn** [comment]
That looks more usable, thanks for the change!

**Comment by gitsf** [comment]
Yes that looks great.
Thanks
