### ISSUE TITLE
Significand amount of filament shows up as "unknown" type when imported into AnkerMake slicer

### ISSUE THREAD

**Issue by chrivers** [just-trey/AnkerMake-M5-Profile#19]
I've tried to use PrusaSlicer to slice models for my Ankermake M5, using the profiles supplied here.

In the process, I've noticed that the following categories of gcode seem to register as "unknown" in AnkerMake:

 - Overhang perimeter
 - Top solid infill
 - Bridge infill
 - Skirt/Brim

For illustration, view in prusaslicer, with only the mentioned types showing:

![image](https://user-images.githubusercontent.com/644439/213947532-d3477e01-105f-41e4-ab71-f2ce59ee2716.png)

View in AnkerMake, with *only* the "unknown" type showing:

![image](https://user-images.githubusercontent.com/644439/213947548-6c308591-7b01-49b2-bd43-9bd40d19459f.png)

Since AnkerMake is (so far) the easiest way to send jobs to the printer, it would be nice if the preview version was free of "unknown", although it doesn't seem to be a dealbreaker for printing.

I can help debug this further, if needed.

**Comment by Xelinor** [comment]
This...isn't really a bug? Those are just features Ankermake slicer doesn't have/support. If it bothers you to see them as unknown, you can load the gcode from the device tab without looking at the preview and send them to the printer from there.

**Comment by just-trey** [comment]
I actually do recommend what @Xelinor suggests as it will preview in that tab as well. I don't think it specificies line types in that preview screen. I do understand it would be nice to have but is outside of my control.

**Comment by chrivers** [comment]
I looked at the generated G-code, and along with the explanation, that makes sense.

Seems AnkerMake just uses different `TYPE: foo` labels, and just happens to understand *some* of the same ones as PrusaSlicer generates... oh well :)
