### ISSUE TITLE
What about SuperSlicer

### ISSUE THREAD

**Issue by AutismeLuxembourg** [just-trey/AnkerMake-M5-Profile#4]
the Profile works fine in PrusaSlicer, but SuperSlicer creates an error on Startup: Preset bundle `AnkerMake` version not found in index: 0.1.0

**Comment by LazeMSS** [comment]
Works fine for me :)

**Comment by just-trey** [comment]
I was able to get it loaded as well. You may have a corrupt file somewhere. did you put it in the correct folder? steps are the same for Prusa Slicer and Super Slicer (just open Super Slicer to show the right configuration folder) 

https://github.com/just-trey/AnkerMake-M5-Profile/tree/master/PrusaSlicer-2.5-M5-Profile#installing-the-profile

![image](https://user-images.githubusercontent.com/10281380/209885592-ff7e8d84-f53a-40a0-9427-980a6be6c75a.png)
