### ISSUE TITLE
Replace bundled zip files with releases

### ISSUE THREAD

**Issue by tomjn** [just-trey/AnkerMake-M5-Profile#7]
It's more reliable/consistent to rely on github releases and link to those.

e.g. https://github.com/just-trey/AnkerMake-M5-Profile/releases/latest always links to the latest release.

This also avoids the problem of nested zip files in automatically generated release/tag archives

**Comment by just-trey** [comment]
I already do use https://github.com/just-trey/AnkerMake-M5-Profile/releases/latest, but I have removed the zip files from the repo in the next release to eliminate the nested zip files. This will go way once that is pushed.
